# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: azuresecrets
- name: imageName
  value: 'iot-device-js:$(build.buildId)'
- name: provisionImage
  value: 'iot-device-js-provision:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'Docker Build Image'
- script: docker build -f Dockerfile-provision -t $(provisionImage) .
  displayName: 'Docker Build Provision'
- script: |
    docker login -u $(clientId) -p $(clientSecret)
    docker tag $(imageName) $(containerRegistry)/iot-device-js:latest
    docker tag $(provisionImage) $(containerRegistry)/iot-device-js:provision
    docker push $(containerRegistry)/iot-device-js:latest
    docker push $(containerRegistry)/iot-device-js:provision
  displayName: "Docker Push Images"
