version: '3'
services:
  device:
    build:
      context: .
      dockerfile: Dockerfile-provision
    image: $REGISTRY_SERVER/iot-device-js:provision
    deploy:
      replicas: 3
    environment:
      TERM: xterm
      ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID
      ARM_CLIENT_ID: $ARM_CLIENT_ID
      ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET
      ARM_TENANT_ID: $ARM_TENANT_ID
      HUB: $HUB
      EDGE_GATEWAY: $EDGE_GATEWAY
      DPS_HOST: $DPS_HOST
      ID_SCOPE: $ID_SCOPE
