version: '3'
services:
  device:
    build: .
    image: $REGISTRY_SERVER/iot-device-js:latest
    volumes:
      - ./cert:/usr/src/app/cert
    environment:
      DEVICE: $DEVICE
      DEVICE_CONNECTION_STRING: $DEVICE_CONNECTION_STRING
      MESSAGE_INTERVAL: 2000
      LOG_LEVEL: debug
